### ISSUE TITLE
Not able use the add dependency

### ISSUE THREAD

**Issue by arjunktr** [mskimm/ann4s#13]
Hi,

I'm not able to add the dependency, I get "module not found: com.github.mskimm#ann4s_2.11;0.0.3" error with below command.

command: spark-shell --packages "com.github.mskimm:ann4s_2.11:0.0.3"

I face same issue with latest version i.e 0.1.1

**Comment by mskimm** [comment]
The jars are released on Bintray, not Maven central. You need to specify its resolver.

Try
```
spark-shell --packages "com.github.mskimm:ann4s_2.11:0.1.1" --repositories https://dl.bintray.com/mskimm/maven
```

By the way, why do you try the obsoleted 0.0.3?

**Comment by mskimm** [comment]
From the version 0.1.2, it is released to Maven. Now you can
```
spark-shell --packages "com.github.mskimm:ann4s_2.11:0.1.4"
```
