### ISSUE TITLE
Binary index cannot work on native annoy interface

### ISSUE THREAD

**Issue by ryeak47** [mskimm/ann4s#14]
Hi, recently I built the annoy index on spark. I try to load the index with the native annoy interface, and it loaded. However, the method .get_nns_by_item does not work. Other methods such as .get_n_items() worked.

**Comment by mskimm** [comment]
I can not reproduce the problem using given information. Can you give me some sample data to build index?

**Comment by ryeak47** [comment]
> I can not reproduce the problem using given information. Can you give me some sample data to build index?

well, I got it. The index of vectors must start from zeros. However, I make the index from 1 to N. This makes the error. Thank you for your reply.
