### ISSUE TITLE
Benefit of Using Spark with Annoy

### ISSUE THREAD

**Issue by preetim96** [mskimm/ann4s#15]
Hello @mskimm  
This question may be naive because I am new to Spark Community. Can you please share the benefit of Integrating Annoy and Spark Together ?

**Comment by mskimm** [comment]
Above all, It can handle large amounts of data. As mentioned in README, I had built an index of 117M 64-dimensional vectors on Spark Cluster. It is difficult on a single machine (maybe infeasible).

**Comment by preetim96** [comment]
Thanks for replying @mskimm 
Does this increase the Search time as compared to original Annoy?
