### ISSUE TITLE
Retrieve nearest neighbors 

### ISSUE THREAD

**Issue by marilenaoita** [mskimm/ann4s#16]
Hi, thanks for your contribution. I construct the index, but thee doesnt seem to be a way to use it from the "api" perspective. Could you help with this issue? best regards, Marilena

**Comment by mskimm** [comment]
For retrieving, please use [Annoy](https://github.com/spotify/annoy). It supports C++ and Python API. If you are looking for a Scala API, [annoy4s](https://github.com/annoy4s/annoy4s) would be a good option. The output binary is compatible with them.
