### ISSUE TITLE
When I run my code, NoClassDefFound error occurs

### ISSUE THREAD

**Issue by HermioneZhang** [mskimm/ann4s#2]
Can someone help me? I am using scala 2.11.8 and spark 2.1.1.
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/sql/DataFrame

**Comment by mskimm** [comment]
Did you submit the job as http://spark.apache.org/docs/latest/submitting-applications.html ?

**Comment by AnkitaJo** [comment]
Getting the same issue. And I am submitting the job as mentioned in the link. Also, I am following the [example](https://github.com/mskimm/ann4s/blob/master/src/test/scala/ann4s/spark/AnnoySparkSpec.scala).
My dataset is converted into a dataframe successfully. I am not sure why I still get the above error. 
Please can you help with this?

**Comment by mskimm** [comment]
@AnkitaJo It seems to be a problem caused by different Spark versions. As I mentioned in README, the library in bintray is built on 1.6.2. I will support the newer version soon.
