### ISSUE TITLE
is this project binary compatible with annoy?

### ISSUE THREAD

**Issue by erikbern** [mskimm/ann4s#3]
in that case, would love to link to it from the main annoy readme!

**Comment by mskimm** [comment]
I love it, too!
I am a bit embarrassed because I wrote this while studying Scala. I have to keep improving. Thanks!

**Comment by erikbern** [comment]
ok cool – is it binary compatible though? :)

**Comment by mskimm** [comment]
Yes, I implemented as you done.
This code was tested on the Annoy index that was built by Annoy

**Comment by erikbern** [comment]
cool – i've added a link from annoy's readme to this project
