### ISSUE TITLE
Index Building and Neighbor Search on distributed executors

### ISSUE THREAD

**Issue by minnong** [mskimm/ann4s#4]
Hi, this is awesome! I am a newbie to Spark. It seems that the AnnoySpark builds the index and searches neighbors via distributed executors on RDDs? Is that right? Have you compared performances with the original Annoy?

**Comment by mskimm** [comment]
@minnong 

in terms of speed(index building and neighbor search), The original Annoy is super faster than this implementation. in terms of precision and recall, this yields the same results.

The purpose of this implementation is studying Scala and Spark and understanding Annoy implementation.

If I re-implement this project which can be applied to the production, I will let you know. Thanks!

**Comment by bigheiniu** [comment]
hey, do you think use jna will counteract the advantage of spark? Because I think the memory access for C++ code will have disadvantage of efficiency.

**Comment by mskimm** [comment]
To persist data (eg. float array), serialization and deserialization are required that are also required in JNA (perhaps).  I think to compare them, the rest parts such as dot product between two vectors are considered.

So, JNA which computes two vectors in the native library can be more efficient than this.

**Comment by mskimm** [comment]
Please check out https://github.com/mskimm/ann4s/issues/9. I will focus on building index on Apache Spark.
